// examples/vue/src/App.vue
<script setup lang="ts">
import { notate } from 'animate-notation'
import { onMounted, onUnmounted, ref } from 'vue'

const target = ref<HTMLDivElement | null>(null)
const vite = ref<ReturnType<typeof notate> | null>(null)
const vue = ref<ReturnType<typeof notate> | null>(null)
const title = ref<HTMLHeadingElement | null>(null)
const animate = ref<ReturnType<typeof notate> | null>(null)
onMounted(() => {
  vite.value = notate(target.value!.children[0] as HTMLElement, 'o', {
    opacity: 0.6,
  })
  vue.value = notate(target.value!.children[1] as HTMLElement, 'box', {
    opacity: 0.6,
  })
  animate.value = notate(title.value!, '=', {
    opacity: 0.1,
  })
})
onUnmounted(() => {
  vite.value?.remove()
  vue.value?.remove()
  animate.value?.remove()
})
</script>

<template>
  <div ref="target" class="container">
    <a
      href="https://vite.dev" target="_blank"
      @mouseover="vite?.show(600)" @mouseleave="vite?.hide(200)"
    >
      <h2>Vite</h2>
    </a>
    <a
      href="https://vuejs.org/" target="_blank"
      @mouseover="vue?.show(600)" @mouseleave="vue?.hide(200)"
    >
      <h2>Vue</h2>
    </a>
  </div>
  <h1
    ref="title" @mouseover="animate?.show(600)"
    @mouseleave="animate?.hide(200)" v-text="'Vite + Vue'"
  />
</template>

<style scoped>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
}
.container>a {
  display: inline-block;
  padding: .25rem;
  line-height: 0;
}
.logo {
  height: 6em;
  padding: 1.5em;
}
</style>

// examples/react/src/App.tsx
import { notate } from 'animate-notation'
import { useEffect, useRef } from 'react'
import './App.css'

function App() {
  const target = useRef<HTMLDivElement>(null)
  const vite = useRef<ReturnType<typeof notate>>(null)
  const react = useRef<ReturnType<typeof notate>>(null)
  const title = useRef<HTMLHeadingElement>(null)
  const animate = useRef<ReturnType<typeof notate>>(null)

  useEffect(() => {
    vite.current = notate(target.current!.children[0] as HTMLElement, 'o', {
      opacity: 0.6,
    })
    react.current = notate(target.current!.children[1] as HTMLElement, 'box', {
      opacity: 0.6,
    })
    animate.current = notate(title.current!, '=', {
      opacity: 0.1,
    })
    return () => {
      vite.current?.remove()
      react.current?.remove()
      animate.current?.remove()
    }
  }, [])

  return (
    <>
      <div ref={target} className="container">
        <a
          href="https://vite.dev"
          target="_blank"
          onMouseOver={() => vite.current?.show(600)}
          onMouseOut={() => vite.current?.hide(200)}
        >
          <h2>Vite</h2>
        </a>
        <a
          href="https://react.dev"
          target="_blank"
          onMouseOver={() => react.current?.show(600)}
          onMouseOut={() => react.current?.hide(200)}
        >
          <h2>React</h2>
        </a>
      </div>
      <h1
        ref={title}
        onMouseOver={() => animate.current?.show(600)}
        onMouseOut={() => animate.current?.hide(200)}
      >
        Vite + React
      </h1>
    </>
  )
}

export default App
